# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-06 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
